openapi: 3.0.2
info:
  title: Bookshelf API
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: development
paths:
  /samples:
    get:
      operationId: getBooks
      responses:
        '200':
          $ref: '#/components/responses/books'
          description: Ok
    post:
    responses:
        '200':
          description: Ok
components:
  schemas:
    book:
      type: object
      properties:
        id:
          type: integer
          example: 01
        title:
          type: string
          example: Example title
        author:
          type: string
          example: Teresa
        finished_at:
          type: string
          format: date
          example: '2023-01-01'
      required:
        - id
        - title
        - author
    books:
      type: object
      properties:
        books:
          type: array
          items:
            $ref: '#/components/schemas/book'
      required:
        - books
  responses:
    books:
      description: Array of books
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/books'
