version: "3.7"
services:
  node:
    container_name: node_express
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/backend
    tty:  true
    ports:
      - 3000:3000
    restart: always

  postgres:
    container_name: postgres
    image: postgres:13
    ports:
      - 5432:${DB_PORT}
    volumes:
      - db_data:/var/lib/posrgresql/data
      - ./db:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

volumes:
  db_data: {}
