version: '3'
services:
  db:
    build: .
    container_name: bookshelf_container
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 3000:3000
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test_db
